#php_install.yml

- name: install epel
  yum:
    name: "{{packages}}"
  vars:
    packages:
      - epel-release

- name: rpm remi repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: install php
  yum:
    name: 
      - php 
      - php-pear
      - php-devel
      - php-mysql
      - php-mbstring
      - php-gd
      - php-pdo
      - php-xml
      - php-mcrypt
    enablerepo: 
      - epel
      - remi
      - remi-php56

- name: php用 sample ファイル配置
  shell: "echo '<?php phpinfo() ?>' > /var/www/html/info.php"
  args:
    creates: "/var/www/html/info.php"

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
