#update_package.yml

- name: update
  yum:
    name: '*'
    state: latest
  register: test_ret

- name: check
  yum:
    name: '*'
    state: latest
  register: test_ret

- name: return
  debug:
    msg: "{{test_ret.results}}"
