@echo off
rem ------------------------------------------------
rem Copyright (c) 2019 da-machi
rem This software is released under the MIT License.
rem http://opensource.org/licenses/mit-license.php
rem ------------------------------------------------

rem ------------------------------------------------
rem AutomaticGenerationProperties(JAVA)
rem 機能概要：プロパティファイルと対になるJAVAソースを自動生成するバッチ
rem 第一引数：プロパティ変数を羅列したファイル
rem ------------------------------------------------

rem カレントパスをバッチファイルのあるパスに変更
cd %~dp0
rem 遅延環境変数の展開
setlocal enabledelayedexpansion

rem 引数ファイル名を各生成ファイル名とする
rem 参考(http://orangeclover.hatenablog.com/entry/20101004/1286120668)
set objName=%~n1

set propertiesFile=%objName%.properties
set javaFile=%objName%.java

rem 各ファイル初期化
echo #automatically generated by bat                        > %propertiesFile%
echo //automatically generated by bat                       > %javaFile%

rem 各出力
echo import java.io.FileInputStream;                        >> %javaFile%
echo import java.io.IOException;                            >> %javaFile%
echo import java.util.Properties;                           >> %javaFile%
echo.                                                       >> %javaFile%
echo public class %objName% {                               >> %javaFile%
echo     private static %objName% ins = null;               >> %javaFile%
for /f %%a in (%1) do (
echo %%a=>>%propertiesFile%
echo     private String %%a;                                >>%javaFile%
)
echo.                                                       >> %javaFile%
echo     /**                                                >> %javaFile%
echo     * param is properties file path                    >> %javaFile%
echo     * @param str                                       >> %javaFile%
echo     * @return                                          >> %javaFile%
echo     */                                                 >> %javaFile%
echo     public static %objName% getinstance(String str) {  >> %javaFile%
echo         if (ins == null) {                             >> %javaFile%
echo             ins = new %objName%(str);                  >> %javaFile%
echo         }                                              >> %javaFile%
echo         return ins;                                    >> %javaFile%
echo     }                                                  >> %javaFile%
echo.                                                       >> %javaFile%
echo private %objName%(String path) {                       >> %javaFile%
echo.                                                       >> %javaFile%
echo     Properties prop = new Properties();                >> %javaFile%
echo.                                                       >> %javaFile%
echo     try {                                              >> %javaFile%
echo         prop.load(new FileInputStream(path));          >> %javaFile%
echo     } catch (IOException e) {                          >> %javaFile%
echo         e.printStackTrace();                           >> %javaFile%
echo     }                                                  >> %javaFile%
echo.                                                       >> %javaFile%
for /f %%a in (%1) do (
echo    %%a = prop.getProperty^(^"%%a^"^);                  >>%javaFile%
)
echo.                                                       >> %javaFile%
echo }                                                      >> %javaFile%
for /f %%a in (%1) do (
echo    public String get_%%a^(^){                          >>%javaFile%
echo         return %%a;                                    >>%javaFile%
echo    }                                                   >>%javaFile%
)
echo.                                                       >> %javaFile%
echo }                                                      >> %javaFile%


exit /b