- hosts: test
  vars:
    title_var: doku_wikiのsetup用playbook
    src_url: http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
  tasks:
    - debug:
        msg: "{{title_var}}"

    - name: update_package
      include: parts/update_package.yml

    - include: parts/install_httpd.yml

    - include: parts/install_php.yml

    - include: parts/Invalidation_selinux.yml


    - name: 今回必要なもののインストール
      yum:
        name: "{{packages}}"
      vars:
        packages:
          - wget

    - name: wget doku_wiki
      shell: wget "{{src_url}}"

    - name: ファイルの解凍
      shell: tar zxfvp dokuwiki-stable.tgz

    - name: ファイルの配置 -> www/html
      shell: mv dokuwiki-2* /var/www/html/dokuwiki

    - name: apacheの権限付与
      shell: chown -R apache:apache /var/www/html/dokuwiki

    - name: update_package
      include: parts/setting_systemd_httpd.yml
