- hosts: nodes-test
  vars:
    sample_var: test dayo !!!
  tasks:
    - debug:
        msg: "{{sample_var}}"
  
    - name: update packages
      yum:
        name: '*'
        state: latest
      register: test_ret

    - name: update packages debug result
      debug:
        msg: "{{test_ret.results}}"
